Repository GSM-MSG/SMS-FrontEnd, pull requests merged in 2024-05, with the labels that each got.

#296 [#295] 의존성 추가
  .github/workflows/SMS-app-CI.yml
  .github/workflows/SMS-shared-CI.yml
  package.json
  packages/app/package.json
  pnpm-lock.yaml
Labels: ⚙ Setting

#298 [#297] SMS 인증제 Textfield 컴포넌트 퍼블리싱
  packages/shared/src/atoms/Input/index.stories.tsx
  packages/shared/src/atoms/Input/index.tsx
  packages/shared/src/atoms/Input/style.ts
  packages/shared/src/icons/File.tsx
  packages/shared/src/icons/index.mdx
  packages/shared/src/icons/index.ts
  packages/shared/src/molecules/SearchInput/index.tsx
Labels: 3️⃣ Priority: Low

#304 [#303] 회원가입 리렌더링 및 요청 문제 해결
  packages/app/src/features/auth/hook/useLoggedIn.tsx
  packages/app/src/features/register/services/PostTeacherRegisterService/index.tsx
  packages/app/src/pages/register/teacher.tsx
Labels: 🐞 Bug

#309 [#304] SMS 인증제 바로가기 버튼 제한
  packages/app/src/features/global/Header/index.tsx
Labels: 0️⃣ Priority: Critical
