Repository GSM-MSG/SMS-FrontEnd, pull requests merged in 2024-06, with the labels that each got.

#314 [#312] 마이페이지 수정 요구사항 반영
  packages/app/src/features/student/molecules/MyPageForm/index.tsx
  packages/app/src/features/student/molecules/ProfileInputs/index.tsx
  packages/shared/src/molecules/MultiDoubleInput/index.tsx
  packages/shared/src/molecules/MultiInput/index.tsx
Labels: 0️⃣ Priority: Critical

#321 editorconfig 설정 수정
  .editorconfig
  packages/app/src/features/global/Header/index.tsx
  packages/app/src/features/student/molecules/MyPageForm/index.tsx
Labels: ⚙ Setting

#306 [#305] 인증제 컴포넌트 추가
  packages/shared/src/molecules/CertificationForm/Context.tsx
  packages/shared/src/molecules/CertificationForm/Field.tsx
  packages/shared/src/molecules/CertificationForm/Header.tsx
  packages/shared/src/molecules/CertificationForm/Title.tsx
  packages/shared/src/molecules/CertificationForm/index.stories.tsx
  packages/shared/src/molecules/CertificationForm/index.tsx
  packages/shared/src/molecules/CertificationForm/style.ts
  packages/shared/src/molecules/index.ts
Labels: 2️⃣ Priority: Medium, ✨ Feature

#319 [#318] 기업 공유용 학생 프로필 페이지 추가
  packages/app/src/features/student/molecules/ShareStudentDetail/index.tsx
  packages/app/src/features/student/molecules/ShareStudentDetail/style.ts
  packages/app/src/features/student/queries/useShareStudentDetailQuery.tsx
  packages/app/src/features/student/service/ShareStudentDetailApi.ts
  packages/app/src/features/student/templates/ShareStudentTemplate/index.tsx
  packages/app/src/features/student/templates/ShareStudentTemplate/style.ts
  packages/app/src/pages/_app.tsx
  packages/app/src/pages/student/link.tsx
Labels: 2️⃣ Priority: Medium, ✨ Feature

#324 [#323] 다중 input 문제 해결
  packages/shared/src/molecules/CertificationForm/Field.tsx
  packages/shared/src/molecules/CertificationForm/index.stories.tsx
  packages/shared/src/molecules/CertificationForm/style.ts
Labels: 3️⃣ Priority: Low, 🐞 Bug

#326 [#325] SegmentedControl 컴포넌트 수정
  packages/shared/src/atoms/SegmentedControl/Option.tsx
  packages/shared/src/atoms/SegmentedControl/Root.tsx
  packages/shared/src/atoms/SegmentedControl/index.stories.tsx
  packages/shared/src/atoms/SegmentedControl/index.tsx
  packages/shared/src/atoms/SegmentedControl/style.ts
Labels: 2️⃣ Priority: Medium, 🐞 Bug

#328 [#327] 파일 입력 컴포넌트 추가
  packages/shared/src/atoms/FileInput/index.stories.tsx
  packages/shared/src/atoms/FileInput/index.tsx
  packages/shared/src/atoms/FileInput/style.ts
Labels: 2️⃣ Priority: Medium, ✨ Feature

#317 [#301] 프로필 공유 모달 제작
  packages/app/src/features/student/atoms/ProfileShareModalFooter/index.tsx
  packages/app/src/features/student/atoms/ProfileShareModalFooter/style.ts
  packages/app/src/features/student/atoms/ProfileShareModalHeader/index.tsx
  packages/app/src/features/student/atoms/ProfileShareModalHeader/style.ts
  packages/app/src/features/student/atoms/ProfileShareModalSection/index.tsx
  packages/app/src/features/student/atoms/ProfileShareModalSection/style.ts
  packages/app/src/features/student/atoms/ProjectDetail/style.ts
  packages/app/src/features/student/molecules/ProfileSharingModal/index.tsx
  packages/app/src/features/student/molecules/ProfileSharingModal/style.ts
  packages/app/src/features/student/molecules/StudentDetail/index.tsx
  packages/app/src/features/student/molecules/StudentDetail/style.ts
  packages/app/src/features/student/molecules/StudentDetailModal/index.tsx
  packages/app/src/features/student/service/createShareProfilService.ts
  packages/app/src/pages/student/[studentId].tsx
Labels: 2️⃣ Priority: Medium, ✨ Feature

#332 [#331] FileInput 문제 해결
  packages/shared/src/atoms/FileInput/index.stories.tsx
  packages/shared/src/atoms/FileInput/index.tsx
  packages/shared/src/atoms/FileInput/style.ts
Labels: 3️⃣ Priority: Low, 🐞 Bug

#336 redux 설정 수정
  packages/app/package.json
  packages/app/src/features/dialog/molecules/DialogProvider.tsx
  packages/app/src/features/modal/providers/ModalProvider.tsx
  packages/app/src/features/student/queries/useStudentListQuery.tsx
  packages/app/src/features/toast/components/ToastContainer/index.tsx
  packages/app/src/pages/_app.tsx
  packages/app/src/store/index.ts
  pnpm-lock.yaml
Labels: 2️⃣ Priority: Medium, 🌏 Deploy

#334 ErrorWrapper 컴포넌트 추가
  packages/shared/src/atoms/ErrorWrapper/index.stories.tsx
  packages/shared/src/atoms/ErrorWrapper/index.tsx
  packages/shared/src/atoms/ErrorWrapper/style.ts
Labels: 3️⃣ Priority: Low, ♻️ Refactor, ✨ Feature
